# Generated by Django 4.2.5 on 2023-10-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TurismoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='fecha_de_entrega',
            new_name='fechaDeSalida',
        ),
        migrations.RenameField(
            model_name='natal',
            old_name='fecha_de_entrega',
            new_name='fechaDeSalida',
        ),
        migrations.RenameField(
            model_name='paquetes',
            old_name='fecha_de_entrega',
            new_name='fechaDeSalida',
        ),
        migrations.RenameField(
            model_name='tailandia',
            old_name='fecha_de_entrega',
            new_name='fechaDeSalida',
        ),
    ]
