# Generated by Django 4.2.5 on 2023-11-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurismoApp', '0006_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='subjet',
            field=models.CharField(max_length=40),
        ),
    ]
